/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./components/ui/badge.vue')['default']
    Button: typeof import('./components/ui/button.vue')['default']
    Card: typeof import('./components/ui/card.vue')['default']
    Dialog: typeof import('./components/ui/dialog.vue')['default']
    DialogClose: typeof import('./components/ui/dialog-close.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog-description.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog-footer.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog-header.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog-title.vue')['default']
    DropdownMenu: typeof import('./components/ui/dropdown-menu.vue')['default']
    DropdownMenuContent: typeof import('./components/ui/dropdown-menu-content.vue')['default']
    DropdownMenuItem: typeof import('./components/ui/dropdown-menu-item.vue')['default']
    DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu-separator.vue')['default']
    DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu-trigger.vue')['default']
    EmptyState: typeof import('./components/ui/empty-state.vue')['default']
    Input: typeof import('./components/ui/input.vue')['default']
    Progress: typeof import('./components/ui/progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./components/ui/scroll-area.vue')['default']
    Select: typeof import('./components/ui/select.vue')['default']
    SelectContent: typeof import('./components/ui/select-content.vue')['default']
    SelectItem: typeof import('./components/ui/select-item.vue')['default']
    SelectLabel: typeof import('./components/ui/select-label.vue')['default']
    SelectTrigger: typeof import('./components/ui/select-trigger.vue')['default']
    SelectValue: typeof import('./components/ui/select-value.vue')['default']
    Separator: typeof import('./components/ui/separator.vue')['default']
    Skeleton: typeof import('./components/ui/skeleton.vue')['default']
    Table: typeof import('./components/ui/table.vue')['default']
    TableBody: typeof import('./components/ui/table-body.vue')['default']
    TableCell: typeof import('./components/ui/table-cell.vue')['default']
    TableHead: typeof import('./components/ui/table-head.vue')['default']
    TableHeader: typeof import('./components/ui/table-header.vue')['default']
    TableRow: typeof import('./components/ui/table-row.vue')['default']
    Tabs: typeof import('./components/ui/tabs.vue')['default']
    TabsContent: typeof import('./components/ui/tabs-content.vue')['default']
    TabsList: typeof import('./components/ui/tabs-list.vue')['default']
    TabsTrigger: typeof import('./components/ui/tabs-trigger.vue')['default']
  }
}
